### ISSUE TITLE
first start is failing: samples.renardo.org redir error ?

### ISSUE THREAD

**Issue by isAAAc** [e-lie/renardo#13]
- launch renardo
- select Autostart
- Download renardo default samples pack

```
SSLError: HTTPSConnectionPool(host='samples.renardo.org', port=443): Max retries exceeded with url: /0_foxdot_default/ (Caused by 
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate 
(_ssl.c:992)')))
Quitting...
```

with a web browser, https://samples.renardo.org  redirect to a yunohost admin panel ;)

thx for your work, 
isAAAc

**Comment by e-lie** [comment]
Samples file server is back. I'm gonna add probe/redondancy to avoid that

**Comment by stone** [comment]
I think it happened again, http://samples.renardo.org gives 503 and https://samples.renardo.org gives SSL errors.

**Comment by vincentreynaud** [comment]
I can confirm!
